{% set name = "equinox" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5eccfb1d41316c8e86730f0a1acf3b1114768ecfd7836b05e4a3e008c7e1d646

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - jax >=0.3.4

test:
  imports:
    - equinox
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/patrick-kidger/equinox
  summary: Neural Networks in JAX.
  description: |
    Callable PyTrees and filtered JIT/grad transformations
    => neural networks in JAX.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.kidger.site/equinox/
  dev_url: https://github.com/patrick-kidger/equinox

extra:
  recipe-maintainers:
    - dhirschfeld
