{% set name = "equinox" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db991934c9edd7978664bf4a09e6d2c8d6dcb6655b02ab00a93e13f4f5a3a87f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - jax >=0.4.4
    - jaxtyping >=0.2.14
    - typing-extensions >=4.5.0

test:
  imports:
    - equinox
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/patrick-kidger/equinox
  summary: Neural Networks in JAX.
  description: |
    Callable PyTrees and filtered JIT/grad transformations
    => neural networks in JAX.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.kidger.site/equinox/
  dev_url: https://github.com/patrick-kidger/equinox

extra:
  recipe-maintainers:
    - dhirschfeld
